name: Deploy Svelte to Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
